language: go
sudo: false
go:
- 1.5
before_install:
- echo -e "machine github.com\n login $TRAVIS_CI_TOKEN" >> ~/.netrc
install:
- DST=~/gopath/src/github.com/nats-io
- mkdir -p "$DST"
- git clone --depth=1 --quiet https://github.com/nats-io/stan-server.git "$DST"/stan-server
- go get -t ./...
- go get golang.org/x/tools/cmd/cover
- go get github.com/mattn/goveralls
script:
- go fmt ./...
- go vet ./...
- go test -i -race ./...
- go test -v -race -p=1 ./...
- GOMAXPROCS=1 go test -v -p=1 -covermode=count -coverprofile=coverage.out
- "$HOME/gopath/bin/goveralls -coverprofile coverage.out -service travis-pro"
env:
  global:
  - secure: KEDPc6qe850+2bfApJHifCFG4d+9b4ZOOSgpTL7Xy8Raw0ZL5jC8Egdl1Ds+TDahJ8ptxoMbyIYHYdVEvohJsIeFRmYZmStCo2oNkdbbGZgM1XTNybo/RxKtXtW+9Fr/8SJOBrworNacq2wrtKAsQuxSaZfw1hET9wUqZaixwJlaGlN5xDqiZbOkFF5q8oRt9hguPUs13XqjPQBH6m/F8AfCtiipwxP/jgYopTtTGbkg3ZQi/tpHceQg0DnZrVwT3TWR4o6Aqqvls2yCVHCUyWX14m6gLyE+7utxDRUdw46TWaeTpUtjpAcg3zFEJrjf/KG7WJ0EASqcEN2wWfmB3VdDVCfz8vMiYWcX9I8emcr7Q6RDA+JXqSRM13lcqrD5CrBZlJkt3CyYDZ+A8E8p4Etc0yvhUAbsAnjZkwDwdzntMVgvaAuu0pX2zus5H9LAfPiv7QnyUyWWx8jqpUYQ73iT7tefPHy+lhKwl9HYqax5jIbyz+okX5DwIr0mDgSSHlvM/umrAUl3h8f2D1nZ/m+tynshr+lNQYgFhH1vwW/0JBJWenvpMPtaY/wALVz01r90JmdbTAY1mnpLMjLeaC8s+4GOurPm0JHGly/qcMXxSv0OPt47uUkDTo6/ebCLJzbQlHl3kSYquyiXmw5j+n7kOd68e7VokWy+6PmQDRE=
  - secure: Rt/tkZFd6toK8tVMiui6ko0RsCtOnuSasC4N5FJj/L//NN5Kcd60C+OMbdhdV2f/PnMQeb6nPyR72g0PHDER/8qkTaG9auEOqyjmjEa1IgriqipVo4SAdNYAPW4heRSmQL7Upiusjy5xDFcSBDE8ua0Rn1VUaqtX20BvfURp4w128HnsqlSRYuo/iSbsOt27FdvNAGknuGtm00OgvZpJ424ex9RzEvQZlDtFSgM0edd/ije2CYEAWCiU2cEMjyijFOfaWfSBPkDTupbQse5HLqhE4uJIorN9CWBd2E43/S4aJ7gMB7HkyghtDZ6LmRD6qWkxghfdedTgj3YbR8ymtJVXr8GsAp2YVoG5v161fecwYTB2yDerJLRuoMSp6fJvDYpP7gLhr/xCMhkFgTD4eozWFUr1dp168T1XPWZiFBtfT9ZrY8M03K6NEj24XqBRF1jfewRceXNIuYqmdN6JUWkxQ/nBjJ0NgHmU7jiDLeEryv81Uq5bDk1eASzxZvtz0OgJVk9lhTGDu+IbWJnW1tdSDnlbcbYkYencvChkJL1WzcUwbh+bd7Rks60LqNG62ARh/+WMGlaMtpxszO66H2fvV/XV4tm9Wr8XhovJOWrg9ommBPkRYRMA5a3eTjkpQ81fghe/2CUMlp0EvdE5r59U/qnXoGSroJ8oAGfYT0w=
